### ISSUE TITLE
finding a camera

### ISSUE THREAD

**Issue by Tridy** [jamesballs/SimpleWMI#1]
Hi.
Is there a way of finding camera information?
I would like to verify if it is currently on or off.
Thanks!

**Comment by jameshball** [comment]
Thanks for making an issue!

You should be able to use the [Win32_PnPEntity](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-pnpentity) class that can be accessed via Win32.PnPEntity. The link provided all of the properties that you can access for the plug & play devices on your machine.

https://community.spiceworks.com/topic/2273558-check-if-webcam-being-used-with-script-reading-hardware-properties-values This post suggests that you can find all cameras by filtering on only the plug & play devices that contain "camera" in the caption.

This would be something like:

`IEnumerable<dynamic> cameras = WMIQuery.GetAllObjects(Win32.PnPEntity).Where(c => c.Caption.ToLower().Contains("camera"));`

I'm not sure how you would check whether it's on or off, but you might be able to use the Availability property which is explained more here https://powershell.one/wmi/root/cimv2/win32_pnpentity

Let me know if that helps :)

**Comment by Tridy** [comment]
Thanks! I was able to find the camera through the PnP devices, actually 3 of them, probably _usb_, _video_ and _mic_ as separate devices.
```
IEnumerable<dynamic> cameras = WMIQuery.GetAllObjects(Win32.PnPEntity).Where(c => c.Caption != null && c.Caption.ToLower().Contains("logitech brio"));

foreach (dynamic item in cameras)
{
    Console.WriteLine($"Device ID: {item.DeviceID} | {item.PNPClass} | {item.Caption} | {item.StatusInfo} | {item.Availability}");
    Console.WriteLine();
}
```
wihich gives me the output:
```
Device ID: USB\VID_046D&PID_085E\342F89AC | USB | Logitech BRIO |  |
Device ID: USB\VID_046D&PID_085E&MI_03\A&24F7C753&0&0003 | MEDIA | Logitech BRIO |  |
Device ID: USB\VID_046D&PID_085E&MI_00\A&24F7C753&0&0000 | Image | Logitech BRIO |  |
```
however getting the status, like whether the camera is on or off does not work with Availability since I get null regardless whether the camera is on or off. I could not see any dynamic properties that change when I toggle the camera on/off.

Thanks anyway. I will try to explore more if I can ping the camera in some way and it will show that it is busy or similar.
